SystemOrganization addCategory: #MyNewLaserGame!
SystemOrganization addCategory: #'MyNewLaserGame-Examples - Board Game'!
SystemOrganization addCategory: #'MyNewLaserGame-Examples - ButtonPanel'!
SystemOrganization addCategory: #'MyNewLaserGame-Examples - Buttons'!
SystemOrganization addCategory: #'MyNewLaserGame-Examples - CellElement'!
SystemOrganization addCategory: #'MyNewLaserGame-Examples - Grid'!
SystemOrganization addCategory: #'MyNewLaserGame-Examples-Buttons'!
SystemOrganization addCategory: #'MyNewLaserGame-Graphic-Leds'!
SystemOrganization addCategory: #'MyNewLaserGame-Graphics-Buttons'!
SystemOrganization addCategory: #'MyNewLaserGame-Graphics-Cells'!
SystemOrganization addCategory: #'MyNewLaserGame-Graphics-ControlPanel'!
SystemOrganization addCategory: #'MyNewLaserGame-Graphics-Game'!
SystemOrganization addCategory: #'MyNewLaserGame-Graphics-Grid'!
SystemOrganization addCategory: #'MyNewLaserGame-LaserGame'!
SystemOrganization addCategory: #'MyNewLaserGame-Model-Cells'!
SystemOrganization addCategory: #'MyNewLaserGame-Model-ControlPanel'!
SystemOrganization addCategory: #'MyNewLaserGame-Model-Directions'!
SystemOrganization addCategory: #'MyNewLaserGame-Model-Grid'!
SystemOrganization addCategory: #'MyNewLaserGame-Model-LaserBeam'!
SystemOrganization addCategory: #'MyNewLaserGame-Model-Leds'!
SystemOrganization addCategory: #'MyNewLaserGame-Tests-CellElements'!
SystemOrganization addCategory: #'MyNewLaserGame-Tests-Cells'!
SystemOrganization addCategory: #'MyNewLaserGame-Tests-Grid'!
SystemOrganization addCategory: #'MyNewLaserGame-Tests-MirrorCell'!
